### ISSUE TITLE
readthedocs config/integration going stale

### ISSUE THREAD

**Issue by anntzer** [scikit-sparse/scikit-sparse#100]
@jellis18 @AaronDJohnson A long time ago back when I maintained scikit-sparse I had set up readthedocs integration, but that seems to not be working anymore, and readthedocs is also warning me that the config for the doc build is going stale.  If you give me your readthedocs usernames I can make you admins of the RTD integration too; otherwise I can perhaps just delete the online docs.

**Comment by AaronDJohnson** [comment]
Hi Antony,

Sorry for the delay in response, I've been pretty busy for the past week....

My username on readthedocs is the same as my GitHub username: AaronDJohnson.

All the best,
Aaron
________________________________
From: Antony Lee ***@***.***>
Sent: Monday, August 7, 2023 9:55 AM
To: scikit-sparse/scikit-sparse ***@***.***>
Cc: Aaron ***@***.***>; Mention ***@***.***>
Subject: [scikit-sparse/scikit-sparse] readthedocs config/integration going stale (Issue #100)


@jellis18<https://github.com/jellis18> @AaronDJohnson<https://github.com/AaronDJohnson> A long time ago back when I maintained scikit-sparse I had set up readthedocs integration, but that seems to not be working anymore, and readthedocs is also warning me that the config for the doc build is going stale. If you give me your readthedocs usernames I can make you admins of the RTD integration too; otherwise I can perhaps just delete the online docs.

**Comment by anntzer** [comment]
I invited you to be a maintainer.  Enjoy :)
