### ISSUE TITLE
Installation fails on Colab / Mac(Terminal)

### ISSUE THREAD

**Issue by aymuos15** [scikit-sparse/scikit-sparse#104]
Install Code: !pip install scikit-sparse/pip install scikit-sparse

**Log**

Collecting scikit-sparse
  Downloading scikit-sparse-0.4.12.tar.gz (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 kB 4.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from scikit-sparse) (1.23.5)
Requirement already satisfied: scipy>=0.19 in /usr/local/lib/python3.10/dist-packages (from scikit-sparse) (1.11.2)
Building wheels for collected packages: scikit-sparse
  error: subprocess-exited-with-error
  
  × Building wheel for scikit-sparse (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for scikit-sparse (pyproject.toml) ... error
  ERROR: Failed building wheel for scikit-sparse
Failed to build scikit-sparse

**Error**

ERROR: Could not build wheels for scikit-sparse, which is required to install pyproject.toml-based projects

Exact same error in both cases.

**Comment by matospiso** [comment]
Hi @aymuos15, 

you are likely missing the core dependency for this package -- [SuiteSparse](https://github.com/DrTimothyAldenDavis/SuiteSparse).

In Colab, you can solve this problem by installing SuiteSparse with `apt` before installing scikit-sparse:
```
!apt-get install libsuitesparse-dev
!pip install scikit-sparse
```
On Mac, it should be possible to install SuiteSparse with `brew` (however you will need to set some environment variables so that `pip install` can find the installation directory), see [installation guide](https://github.com/scikit-sparse/scikit-sparse#installation).
