### ISSUE TITLE
sksparse.cholmod.CholmodError: inconsistent use of complex array

### ISSUE THREAD

**Issue by CheLamVien** [scikit-sparse/scikit-sparse#127]
Dear all, 

I am aware that If we did a real factorization, we can't solve complex rhs. 
I want to decompose a new matrix and then solve it with complex rhs. An alternative is to convert this matrix to complex before factorization. However, Cholesky decomposition of the complex matrix with 0j is 1.13 s, whereas the Cholesky decomposition of the real matrix is 0.8 s. Time is really important to my application. Therefore, it would be great if I could perform the Cholesky decomposition of the real matrix. Then, somehow convert it to a complex type. Using Numpy, I can do it like: 
```
L, low = cho_factor(A)
L = L.astype(complex)
x = cho_solve((L, low), b)
```

Is there a way to handle this in scikit-sparse?

Best regards, 
Vien Che

**Comment by DrTimothyAldenDavis** [comment]
I don't know how this would work in python, but you can factorize a real matrix and solve with a complex right-hand-side vector by solving for the reals and imag part separately.  In MATLAB for example (not Cholesky but the same thing would for that):

```
>> A = rand (4)

A =

    0.8147    0.6324    0.9575    0.9572
    0.9058    0.0975    0.9649    0.4854
    0.1270    0.2785    0.1576    0.8003
    0.9134    0.5469    0.9706    0.1419

>> b = rand (4,1) + 1i*rand(4,1)

b =

   0.4218 + 0.6557i
   0.9157 + 0.0357i
   0.7922 + 0.8491i
   0.9595 + 0.9340i

>> A\b

ans =

  17.2819 +11.5872i
   0.8395 + 2.4249i
 -15.9067 -11.3994i
   1.0883 + 0.6236i

>> A\real(b)

ans =

   17.2819
    0.8395
  -15.9067
    1.0883

>> A\imag(b)

ans =

   11.5872
    2.4249
  -11.3994
    0.6236
```

So in python, b was your complex right-hand-side vector, you could convert it into an n-by-2 matrix, say B, where the 1st column of B was real(b) and the 2nd column of B was imag(b), and B is real not complex.  Then solve A*X=B.  That gives a solution X that is n-by-2, where X is real.  To create your complex solution, x = X(:,1) + i*X(:,2), since the 1st column of X is the real part of x, and the 2nd column of X is the imaginary part of x.

**Comment by CheLamVien** [comment]
Dear Prof. Davis, 

Thank you for your suggestion. It works very well. 

Best regards, 
Vien Che
