### ISSUE TITLE
CholmodNotPositiveDefiniteError inconsistent

### ISSUE THREAD

**Issue by mirimo1995** [scikit-sparse/scikit-sparse#58]
I am trying to use the cholesky decomposition to invert a sparse matrix and I found this great package to help me on my problem. 
My issue is that I keep getting CholmodNotPositiveDefiniteError although I verified with the eigenvalues that my matrix is positive and I tried adding small positive diagonal matrix but it didn't work. Here's my notebook 

Could you please help me on this ?
<img width="1311" alt="Screenshot 2020-07-08 at 11 28 29" src="https://user-images.githubusercontent.com/29410989/86902383-299bca00-c10e-11ea-9b09-49d66d979e4c.png">

**Comment by mirimo1995** [comment]
@AlexGrig @jor-

**Comment by jor-** [comment]
You can not calculate a Cholesky decomposition of your matrix, because it is (numerically) not positive definite. Even if you verified that your matrix has only positive eigenvalues, it might be that you can not decompose it due to numerical rounding errors. So the problem is your matrix and not this software. You can try to use another permutation method and maybe you'll be lucky that you can calculate a decomposition. However, I would not expect it to be numerically very accurate.

**Comment by mirimo1995** [comment]
@jor- Could you please explain what you mean by (numerically) not positive definite. Is that different from the mathematic definition of positive definite. The matrix that I am using is of the form (X^T*X) which is symmetric positive by definition and by adding an eye matrix multiplied by a positive constant it makes it positive definite.

**Comment by jor-** [comment]
It might be that your matrix is positive definite but calculations on a computer are usually affected by numerical errors because, for example, some numbers can not be exactly represented on a computer. Thus it might be that even a positive definite matrix can not be decomposed by a computer. This is usually the case when the matrix is close to singular. Your matrix X^T X is symmetric positive semidefinite. But it might be singular if X has not full rank. Adding an eye matrix multiplied by a positive constant makes the matrix positive definite. But if the constant is small, it might still be close to singular and thus not numerically positive definite. However for a big constant this matrix should be numerically positive definite as well.

**Comment by mirimo1995** [comment]
Thank you for reaching out. 
Actually, I am getting the error for values [0.001, 0.01, 0.1] for  epsilon , epsilon being the positive constant that I put on my eye matrix. I think these values are quiet big to be rounded to zero, espicially that if I don't add the matrix X^TX, the decomposition works for very small epsilons (10e-6) but when I add the matrix it only works when epsilon is equal to one. Would you agree on the fact that saying that the matrix is not positive definite in this case is inconsistent and could this be related to the sparsity of X or its size ?
