### ISSUE TITLE
Wrappers license?

### ISSUE THREAD

**Issue by jseabold** [scikit-sparse/scikit-sparse#6]
I'm curious what makes this BSD-incompatible. You're not shipping any of the CHOLMOD source right? How is this different from scipy.sparse.linalg.umfpack? I'm sure you know better than I, so I'm just wondering.

I've started needing things in SuiteSparse for my own work, and I'm using the LU decomposition from scipy. Having Cholesky in the same place would be nice.

**Comment by jor-** [comment]
Although this discussion is somewhat older, I would be glad if someone could help me understanding this licence clutter. Maybe @njsmith?
A part of CHOLMOD is under GPL and the rest under LGPL. So if CHOLMOD would be included in scikit-sparse, it is clear that scikit-sparse has to be under GPL as well. But since scikit-sparse does not include CHOLMOD, scikit-sparse is allowed to be under BSD? So the trick is to not-include CHOLMOD? Is scikit-sparseIs nevertheless a derivative work from CHOLMOD?
