### ISSUE TITLE
solving with solve_Lt(b)

### ISSUE THREAD

**Issue by pf4d** [scikit-sparse/scikit-sparse#9]
I seem to have inconsistent results with solve_Lt(b) in comparison to solving with dense matrices and numpy.linalg.linalg.solve function.  Am I missing something ?

Here's the code (un-comment the R and samp parts and delete the cholmod import for regular solve):

``` python
from pylab                  import *
from scipy.sparse           import spdiags
from scikits.sparse.cholmod import cholesky

nx = 50
ny = 50
N  = nx*ny

#  Set up matrix A. Use SciPy's sparse storage.
Adiag   = 4*ones(N)
Asubs   = - ones(N)
Asubs1  = - ones(N)
Asuper1 = - ones(N)

# we must account for the zeroes in the sub and super diagonal
for i in range(1,ny):
  Asubs1[i*nx - 1] = 0
for i in range(1,ny):
  Asuper1[i*nx] = 0

#I      = identity(n)
#L2D    = kron(L1D, I) + kron(I, L1D)  # too slow and not sparse
data   = [Asubs,Asubs1,Adiag,Asuper1,Asubs]
diags  = [-nx, -1, 0, 1, nx]
L2D    = spdiags(data, diags, N, N)
factor = cholesky(L2D)
#R      = cholesky(L2D.todense())
v      = randn(N,1)
samp   = factor.solve_Lt(v)
#samp   = solve(R.T, v)

imshow(reshape(samp,(nx,ny)), cmap='gray')
colorbar()
show()
```

**Comment by kforeman** [comment]
+1 I'm finding the same thing. `scipy.sparse.linalg.solve(scikits.sparse.cholmod.cholesky(A).L().T, b)` gets the same result as `Matrix::solve(t(Matrix::Cholesky(A)), b)`, but different from `scikits.sparse.cholmod.cholesky(A).solve_Lt(b)`.

**Comment by njsmith** [comment]
`solve_Lt` is just a thin wrapper around CHOLMOD.

I suspect that `cholesky(A).solve_Lt(b)` might be equivalent to `solve(cholesky(A).L_D()[0], b)`, i.e., `solve_Lt` is using the `L` from an LDL decomposition instead of an LL decomposition?

**Comment by kforeman** [comment]
Thanks, @njsmith. Just tested it out and it doesn't appear that those two are equivalent, unfortunately.

Digging through `suitesparse`, it looks like as long as `LL` is defined then it should be using L from LL instead of LDL: https://github.com/jluttine/suitesparse/blob/master/CHOLMOD/Cholesky/t_cholmod_ltsolve.c#L37

Not sure where to go from here without digging into suitesparse/CHOLMOD much deeper, but I can confirm that using `scipy.sparse.linalg.solve` is a viable workaround for right now (though I'm not positive how well that plays together with cholesky in terms of preserving sparsity throughout the calculation). 

Let me know if you've got any ideas for things I could look into or if you'd like me to submit a PR which uses `solve` instead.

**Comment by Evfro** [comment]
Hi, are there any updates on the issue? Maybe some workarounds within `scikits.sparse` and not with the help of `scipy.sparse.linalg`? Thanks!

**Comment by jor-** [comment]
`scikits-sparse` returns the same results as `scipy`. The following examples does not throw an AssertError.

```
import numpy as np
import scipy.sparse
import sksparse.cholmod
import scipy.linalg

n  = 10
A = scipy.sparse.random(n, n, density = 0.1)
A = A + A.T + scipy.sparse.eye(n) * n
A = A.tocsc()
b = np.arange(n)

chol = sksparse.cholmod.cholesky(A, ordering_method='natural')
L = chol.L_D()[0].T.todense()

assert np.allclose(chol.solve_Lt(b), scipy.linalg.solve(L, b))
```
Keep in mind that `solve_Lt` uses the L matrix of a LDLt decomposition.

**Comment by Evfro** [comment]
Thanks for clarifying this! It resolves the confusion around using `L` vs `LD`.
